### ISSUE TITLE
make CLI for this

### ISSUE THREAD

**Issue by predictorapi** [RozhakXD/Zefoy#4]
like python Run.py -url tiktok.com/blah blah

maybe also other arguments such as how many times it will send?

**Comment by JamshaidAhmedd** [comment]
Just create a script for it, i just click it and everythinghs runs for me in the background.

@echo off
cd /d C:\Users\Admin\Desktop\QAU\Sem 7\scripts\toktok\Zefoy
python run.py
pause

save it as runpy.ba
tch
