### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Sz4by** [RozhakXD/Zefoy#5]
It doesn't send more views, it sends one and that's it 😅

**Comment by RozhakXD** [comment]
Here adding views works normally, country differences become a problem.

![Image](https://github.com/user-attachments/assets/37dce311-4b2b-4b4d-86c7-46076235d874)

**Comment by Sz4by** [comment]
I don't understand why you have to wait 4 minutes

**Comment by RozhakXD** [comment]
The delay is a regulation from Zefoy to prevent spam, so they use a 5 minute delay for sending the next views!

**Comment by Sz4by** [comment]
And can this be reduced somewhere?
