### ISSUE TITLE
Failed get views

### ISSUE THREAD

**Issue by ExCelXPNX** [RozhakXD/Zefoy#7]
hi i noticed that the script has a problem with " Failed get views form"

**Comment by RozhakXD** [comment]
No, here it works fine. It's possible that you didn't update Tools to the latest version.

```bash
$ cd Zefoy
$ git pull
$ python Run.py
```
![Working](https://github.com/user-attachments/assets/be3d1d13-5ed1-48af-aa81-961962642e72)
