### ISSUE TITLE
iPhone Login Failed Issue

### ISSUE THREAD

**Issue by JamshaidAhmedd** [RozhakXD/Zefoy#8]
![IMG_4729](https://github.com/user-attachments/assets/279f7529-e9b2-409e-b3c0-61e87e1d2241)
I’m using this tool isH and have installed all dependencies.
![IMG_4730](https://github.com/user-attachments/assets/3c4553f5-1387-4464-bbba-8b5564f37117)

**Comment by RozhakXD** [comment]
In Termux everything works fine, maybe the `Tesseract` Library is not installed properly in ISH. you can use the command below:

```
$ apk add tesseract-ocr
$ apk add py3-pip
$ pip install pillow pytesseract
```

You can try again and if the problem persists try using other alternatives like Google Colab.

![Working](https://github.com/user-attachments/assets/870703e7-ae63-42fa-a55c-c546313e0a48)
