### ISSUE TITLE
Cannot identify Image file

### ISSUE THREAD

**Issue by JamshaidAhmedd** [RozhakXD/Zefoy#9]
![image](https://github.com/user-attachments/assets/545aaf30-535b-4e35-8c2a-cdfa0d7c49df)

**Comment by RozhakXD** [comment]
We have identified that this issue occurs exclusively when using Command Prompt or Windows PowerShell, which are unable to process the image correctly. As a solution, we recommend using WSL (Windows Subsystem for Linux) or Termux to ensure proper functionality.

**Comment by JamshaidAhmedd** [comment]
It’s not occurring before but now, especially today.
